### PR TITLE
Added polish translate

### PR DESCRIPTION
**Pull request by meron1122**
Hi, i wrote polish translate.
Feel free to merge :)

### CODE REVIEW

**Comment by m4sk1n** [comment]
Tried to make some little suggestions to make it (imo) better, what do you think?

**Comment by meron1122** [comment]
Feel free to make PR :), i maked this translate without test on live example, so, some phrases can have another context.

**Comment by m4sk1n** [comment]
I guess that for example “center to left/right” is wrong no matter of context…

**Comment by meron1122** [comment]
So fix it, based on my translate and make PR bro

**Comment by sohee-lee7** [comment]
@meron1122  thanks for the contribution

could you fix your PR refer to https://github.com/nhnent/tui.editor/pull/205/files

then I can merge.

**Comment by m4sk1n** [comment]
> So fix it based on my translate and make PR bro

I made my own one, not basing on your

**Comment by meron1122** [comment]
> > So fix it based on my translate and make PR bro
> 
> I made my own one, not based on your

Fine, I close my PR

**Pull request closed without merging**
