### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by jannkiepert**
### Description
Add german language to enhance internationlization.

### CODE REVIEW

**Comment by jannkiepert** [comment]
So I dont really know why this PR includes more than the one commit I made to add the language file. 
Github still says the branches can be merged without conflicts so I hope that's not a problem.

**Comment by kyuwoo-choi** [comment]
@jannkiepert Thank you for your contribution 🎉 

Would you check out **develop** branch and PR to **develop**?
Make another PR, and I'll merge it for sure :)

Thanks!

**Comment by jannkiepert** [comment]
Yes I'll do it later today. I made the commit directly from the github 
website and chose the wrong branch. I'm fairly new to PRs so I'll try 
again to make the change locally via git and then create a PR again.

**Comment by kyuwoo-choi** [comment]
#33 here is a good example you may interest ;)

**Pull request closed without merging**
