### PR TITLE
feat: add customConvertor options to support customization of converetor for editor and viewer

### PR DESCRIPTION
**Pull request by co3k**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
  - These changes only add options of constructors
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

ToastUIEditor and ToastUIEditorViewer now have the customConvertor option.
It helps to support the project specific format (customized Markdown, reST, asciidoc, and others).

### CODE REVIEW

**Comment by kyuwoo-choi** [comment]
Thanks for the contribution @co3k 🎉 
It seems ok. could you provide an example for it, please?

**Comment by co3k** [comment]
@kyuwoo-choi Sure. Where is a good place to show it? In this pull request or some document?

**Comment by kyuwoo-choi** [comment]
@co3k add commits onto co3k:add-support-configure-convertor

**Comment by co3k** [comment]
OK. I'll add it to the example directory lster.

**Comment by co3k** [comment]
Sorry for my late action. I've fixed the commit to include changes of adding examples and resolving conflicts with the latest master branch. Could you review it again?

**Comment by kyuwoo-choi** [comment]
@co3k thank you

I see this commit fails lint. make another commit to fix the style please.

Then It looks good to go. It'll be shipped on 1.3.0

```
/Users/FE/.jenkins/jobs/tui-editor/workspace/test/unit/editor.spec.js
  406:10  error  Missing semicolon  semi

/Users/FE/.jenkins/jobs/tui-editor/workspace/test/unit/viewer.spec.js
  54:6  error  Missing semicolon  semi

✖ 56 problems (2 errors, 54 warnings)
  2 errors, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by co3k** [comment]
@kyuwoo-choi Thanks for your review. I've fixed it by https://github.com/nhnent/tui.editor/pull/236/commits/63071a54be9b4a232513c4d7fd66c0e551257827

**Pull request merged**
