### PR TITLE
feat: added footnotes support (close: #291)

### PR DESCRIPTION
**Pull request by rustamtolipov**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description
Adds markdown-it-footnote (https://github.com/markdown-it/markdown-it-footnote) footnotes support

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by kyuwoo-choi** [comment]
thank you for the contribution @rustamtolipov 

let me take a time to review this PR

**Comment by mu-yu** [comment]
It will be better if there is a toolbar button to set footnote for selected text.

**Comment by sohee-lee7** [comment]
@rustamtolipov We support also wysiwyg mode. This footnote feature only work in makrdown mode. So we could not merge this. I am sorry to say this.

**Comment by sohee-lee7** [comment]
@rustamtolipov 
To merge this feature, I reviewed it again.
When converting to WYSIWYG, the footnote is well converted, but on the other hand, the markdown does not work properly when return to Markdown again.
Could you implement convert to Markdown from Wysiwyg?
screen recording 2019-01-23 at 4 10 28 pm mov

**Comment by sohee-lee7** [comment]
This feature need to more implement about coverting to Wysiwyg.

**Pull request closed without merging**
