### PR TITLE
fix: Make popups absolutely positioned AND children of the toolbar (fix #151, #155)

### LINKED ISSUE #151: Tui editor table popup selector box not aligning with the toolbar table button
## Version 

version 1.0.6

## Test Environment

Windows 10 on Chrome

## Current Behavior

1. Place the tui editor on a page that the page is large enough to scroll vertically. 
2. Scroll down from the top of the page so the scroll bar is not all the way up.
3. Click on the table button on the toolbar. 

The popup table selector box is not aligning with the toolbar button. Depend on how big the page is, the popup table selector may even go out of view.

## Expected Behavior

The popup table selector should always align with the toolbar table button.

### PR DESCRIPTION
**Pull request by jkelin**
I can't seem to be able to reopen https://github.com/nhnent/tui.editor/pull/195, this is a continuation of that PR that makes popups be children of the toolbar (I tried absolutely positioning the toolbar and both headings and table popups work correctly).

If you have any other issues with this PR, please don't close it so I can resolve them. I will try my best to see this fixed in the end :)

### CODE REVIEW

**Comment by kyuwoo-choi** [comment]
Thank you @jkelin 
I changed some code from you.

merging it.

**Comment by kyuwoo-choi** [comment]
I noticed you made changes on the master of your repo.
Making changes on fix branch make your life easier to follow our master.
I always squash merge onto the master branch. 🥂

**Comment by jkelin** [comment]
Awesome, thank you for very much for seeing this through.
Your suggestions are very sound, it is obvious that I don't contribute to OSS as much as I should :)

**Comment by kyuwoo-choi** [comment]
I'm looking forward to another contribution from you 😉 
Have a good day @jkelin

**Pull request merged**
